import { readable, writable } from "svelte/store";
export const page_num = writable(7);
export const hotspots = readable({
  page7: [
    {
      type: "rect",
      coords: [23, 109, 227, 314],
      href: "",
      target: "",
      alt: "",
      title: "gorilla",
    },
    {
      type: "rect",
      coords: [246, 109, 462, 314],
      href: "",
      target: "",
      alt: "",
      title: "monkey",
    },
    {
      type: "rect",
      coords: [481, 109, 687, 314],
      href: "",
      target: "",
      alt: "",
      title: "peach",
    },
    {
      type: "rect",
      coords: [447, 342, 610, 459],
      href: "",
      target: "",
      alt: "",
      title: "ring",
    },
    {
      type: "rect",
      coords: [130, 589, 293, 706],
      href: "",
      target: "",
      alt: "",
      title: "drum",
    },
    {
      type: "rect",
      coords: [447, 589, 610, 705],
      href: "",
      target: "",
      alt: "",
      title: "frog",
    },
    {
      type: "rect",
      coords: [530, 462, 609, 505],
      href: "",
      target: "",
      alt: "",
      title: "g",
    },
    {
      type: "rect",
      coords: [447, 707, 502, 750],
      href: "",
      target: "",
      alt: "",
      title: "g",
    },
    {
      type: "rect",
      coords: [130, 342, 293, 459],
      href: "",
      target: "",
      alt: "",
      title: "stop",
    },
    {
      type: "rect",
      coords: [214, 463, 293, 506],
      href: "",
      target: "",
      alt: "",
      title: "p",
    },
    {
      type: "rect",
      coords: [447, 462, 526, 505],
      href: "",
      target: "",
      alt: "",
      title: "p",
    },
    {
      type: "rect",
      coords: [558, 707, 607, 750],
      href: "",
      target: "",
      alt: "",
      title: "p",
    },
    {
      type: "rect",
      coords: [131, 462, 210, 505],
      href: "",
      target: "",
      alt: "",
      title: "m",
    },
    {
      type: "rect",
      coords: [504, 707, 553, 750],
      href: "",
      target: "",
      alt: "",
      title: "m",
    },
    {
      type: "rect",
      coords: [130, 709, 185, 752],
      href: "",
      target: "",
      alt: "",
      title: "g",
    },
    {
      type: "rect",
      coords: [188, 709, 237, 752],
      href: "",
      target: "",
      alt: "",
      title: "m",
    },
    {
      type: "rect",
      coords: [241, 709, 290, 752],
      href: "",
      target: "",
      alt: "",
      title: "p",
    },
  ],
});
